@baseurl= http://localhost:3000
@authToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyaWFueEBnbWFpbC5jb20iLCJzdWIiOiJjbWNhbG0yd3UwMDAwZnB6Z3k5d2FxbGhpIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTA3OTQzNTcsImV4cCI6MTc1MDc5Nzk1N30.7smSjqrV8TeFV4X6fEPERRKZzdWTVvwZqcE2xsAyfG4


###Get user profile
GET {{baseurl}}/users/get-profile
Authorization: Bearer {{authToken}}

### Update user profile
PUT {{baseurl}}/users/update-profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Brian Mwas",
  "email": "brian@gmail.com"
}


### Delete user account
DELETE {{baseurl}}/users/delete
Authorization: Bearer {{authToken}}